### ISSUE TITLE
KeyError: 'parser_options'

### ISSUE THREAD

**Issue by FengXuas** [thomasowenmclean/tei_transformer#3]
Traceback (most recent call last):
  File "/home/xf/桌面/parse/info_extract.py", line 3, in <module>
    parsed = ParserMethods.parse('1.xml')
  File "/usr/local/lib/python3.6/dist-packages/tei_transformer/transform.py", line 54, in parse
    return etree.parse(textpath, cls.parser())
  File "/usr/local/lib/python3.6/dist-packages/tei_transformer/transform.py", line 34, in parser
    parser = etree.XMLParser(**config['parser_options'])
KeyError: 'parser_options'

This is my code：
from tei_transformer.transform import ParserMethods
parsed = ParserMethods.parse('0.xml')

Why the error？

**Comment by fizzbucket** [comment]
You need a config file like this, https://github.com/fizzbucket/tei_transformer/blob/master/tei_transformer/config.yaml

**Comment by FengXuas** [comment]
I get the confit.yam, but a new question.
Traceback (most recent call last):
  File "/home/xf/桌面/parse/info_extract.py", line 6, in <module>
    transformed_tree = ParserMethods.transform_tree(tree)
TypeError: transform_tree() missing 1 required positional argument: 'persdict'

My code:
from tei_transformer.transform import ParserMethods

xmlpath = '0.xml'
parsed = ParserMethods.parse(xmlpath)
tree = parsed.getroot().find('.//{*}body')
transformed_tree = ParserMethods.transform_tree(tree)
text = '\n'.join(transformed_tree.itertext()).strip()

**Comment by fizzbucket** [comment]
This was written for a scholarly edition which included potted biographies of many people, kept in a seperate xml file 'personlist.xml'. If you don't need this, you could either include a blank personlist.xml or edit the code to take out this requirement -- it should only be a couple of lines.

**Comment by fizzbucket** [comment]
Specifically, I would make the following changes:

in tags.py, edit

```
    @staticmethod
    def transform_tree(tree, persdict, in_body=True):
        """Transform a tree."""
        for tag in sorted(list(tree.getiterator('*'))):
            if tag.localname == 'persName':
                tag.process(persdict, in_body=in_body)
            else:
                tag.process()
        return tree
```

to something like:

```
    @staticmethod
    def transform_tree(tree, persdict, in_body=True):
        """Transform a tree."""
        for tag in sorted(list(tree.getiterator('*'))):
                tag.process()
        return tree
```

And in transform.py, change 

```
    def transform(self, inputpath, personlistpath):
        """Transform xml to tex"""
        body = parser.parse(inputpath).getroot().find('.//{*}body')
        assert body is not None
        tree = parser.transform_tree(body, PersDict(personlistpath))
        return '\n'.join(tree.itertext()).strip()
```
to 

```
    def transform(self, inputpath):
        """Transform xml to tex"""
        body = parser.parse(inputpath).getroot().find('.//{*}body')
        assert body is not None
        tree = parser.transform_tree(body)
        return '\n'.join(tree.itertext()).strip()
```

**Comment by FengXuas** [comment]
I need the personlist.xml, how can i ues it?

**Comment by FengXuas** [comment]
I do as you say ,but the question is not solved.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tei_transformer/tags.py", line 39, in process
    replacement = self.get_replacement()
  File "/usr/local/lib/python3.6/dist-packages/tei_transformer/tags.py", line 85, in get_replacement
    div_type = parent_attrs['type']
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xf/桌面/parse/info_extract.py", line 51, in <module>
    transformed_tree = ParserMethods.transform_tree(tree)
  File "/usr/local/lib/python3.6/dist-packages/tei_transformer/transform.py", line 34, in transform_tree
    tag.process()
  File "/usr/local/lib/python3.6/dist-packages/tei_transformer/tags.py", line 41, in process
    self.raise_()
  File "/usr/local/lib/python3.6/dist-packages/tei_transformer/tags.py", line 59, in raise_
    raise ImplementationError(self)
tei_transformer.tags.ImplementationError: <head xmlns="http://www.tei-c.org/ns/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" n="1.">Introduction</head>

**Comment by fizzbucket** [comment]
Can you please show me the files you are trying to process?

**Comment by FengXuas** [comment]
My tei file is an academic paper exported from Grobid.

[test.txt](https://github.com/fizzbucket/tei_transformer/files/3548833/test.txt)

**Comment by FengXuas** [comment]
My tei file is an academic paper exported from Grobid.
[0.txt](https://github.com/fizzbucket/tei_transformer/files/3548834/0.txt)

**Comment by FengXuas** [comment]
Another question, can your code extract all the info in the tei files?, such as DOI, publisher, etc

**Comment by fizzbucket** [comment]
I think you might be trying to use the wrong tool here. This is meant to produce pdf files for scholarly editions from TEI files, not to transform any given tei file like the one you've shown me. For that you are much better off using one of the many XSLT transformations available.

**Comment by FengXuas** [comment]
Sorry..... 
Thank you !
